namespace ArchivalTibiaV71WorldServer.Io
{
    public enum Tokens
    {
        None,
        Eof,

        /* keywords */
        Id,
        Name,
        Password,
        Position,
        TemplePosition,
        Outfit,
        Level,
        Experience,
        Health,
        MaxHealth,
        Mana,
        MaxMana,
        Capacity,
        MagicLevel,
        MagicLevelExp,
        Fist,
        FistExp,
        Club,
        ClubExp,
        Sword,
        SwordExp,
        Axe,
        AxeExp,
        Distance,
        DistanceExp,
        Shielding,
        ShieldingExp,
        Fishing,
        FishingExp,
        Equipment,
        Head,
        Necklace,
        Backpack,
        Armor,
        Right,
        Left,
        Legs,
        Feet,
        Ring,
        Ammo,
        Inventory,
        Item,
        Container,
        IsAdmin,

        /* symbols etc */
        Unknown,
        LeftParenthesis,
        RightParenthesis,
        LeftBracket,
        RightBracket,
        LeftBrace,
        RightBrace,
        Equals,
        Comma,

        /* values */
        True,
        False,
        String,
        Number,
    }
}